In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
dataset = pd.read_csv('DatasetTransform1.csv')
dataset.head()

,Unnamed: 0,País,Año,Registro,Clasificacion,Clase,Modo_de_acción,Grupo_Químico,I.A.,Marca,...,Precio,Fecha,Mes,Grupo_fabricante/Offshore,Fabricante/Offshore,Timbres,Estado,Documento_Imp.,Cantidad_320,Cantidad_-1
0,0,6425,2018,1,5406,1500,1345,1,1,1,...,27.748333,2018-11-30,291,9,28,135.0,Líquido,1,240.0,240.0
1,1,6425,2018,4,5406,1500,227,109,108,4,...,3.000000,2018-05-22,818,373,35,486.0,Líquido,1,16000.0,16000.0
2,2,6425,2018,4,5406,1500,227,109,108,4,...,3.000000,2018-05-22,818,373,35,353.0,Líquido,1,10000.0,10000.0
3,3,6425,2018,5,5406,1500,227,109,108,5,...,3.530000,2018-08-27,592,63,44,30.0,Líquido,1,200.0,200.0
4,4,6425,2018,5,5406,1500,227,109,108,5,...,3.240000,2018-08-27,592,63,44,130.0,Líquido,1,2025.0,2025.0

In [33]:
from sklearn.model_selection import train_test_split
dataset = dataset.drop(['Fecha'], axis=1)
X = dataset.drop(['Estado'], axis=1)
y = dataset['Estado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=2022)
dataset['Estado'] = pd.get_dummies(y, drop_first=True)

In [34]:
dataset

,Unnamed: 0,País,Año,Registro,Clasificacion,Clase,Modo_de_acción,Grupo_Químico,I.A.,Marca,...,CIF_Q,Precio,Mes,Grupo_fabricante/Offshore,Fabricante/Offshore,Timbres,Estado,Documento_Imp.,Cantidad_320,Cantidad_-1
0,0,6425,2018,1,5406,1500,1345,1,1,1,...,51611.90,27.748333,291,9,28,135.0,0,1,240.0,240.0
1,1,6425,2018,4,5406,1500,227,109,108,4,...,355968.00,3.000000,818,373,35,486.0,0,1,16000.0,16000.0
2,2,6425,2018,4,5406,1500,227,109,108,4,...,222480.00,3.000000,818,373,35,353.0,0,1,10000.0,10000.0
3,3,6425,2018,5,5406,1500,227,109,108,5,...,5299.17,3.530000,592,63,44,30.0,0,1,200.0,200.0
4,4,6425,2018,5,5406,1500,227,109,108,5,...,49246.28,3.240000,592,63,44,130.0,0,1,2025.0,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,6420,6425,2018,10,5406,1500,287,12,12,12,...,70942.66,3.996901,346,1074,56,172.0,0,1,2304.0,2304.0
6421,6421,6425,2019,1,5406,1500,287,12,12,12,...,376966.50,6.200000,611,1074,943,507.0,0,1,7920.0,7920.0
6422,6422,6425,2019,10,5406,1500,287,12,12,12,...,133372.89,3.293636,611,1074,34,264.0,0,1,5280.0,5280.0
6423,6423,6425,2019,10,5406,1500,287,12,12,12,...,182510.73,3.264711,616,1074,34,313.0,0,1,7260.0,7260.0
6424,6424,6425,2019,10,5406,1500,287,12,12,12,...,134434.84,3.325455,818,1074,34,265.0,0,1,5280.0,5280.0

In [35]:
#Weak Modeles
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
#Metrics
from sklearn.metrics import roc_auc_score

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split


from sklearn.preprocessing import StandardScaler #Estandarizador

from sklearn.utils import resample #para bootstraping.


import pandas as pd
import numpy as np

In [36]:
lr = 'LogisticRegression().fit(X_train, y_train)'
svm = 'SVC(gamma="scale", kernel="rbf").fit(X_train, y_train)'
dt = 'DecisionTreeClassifier(criterion="gini", max_depth=4).fit(X_train, y_train)'
knn = 'KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)'
nb = 'GaussianNB().fit(X_train, y_train)'
lda = 'LinearDiscriminantAnalysis(solver="svd", store_covariance=True).fit(X_train, y_train)'
qda = 'QuadraticDiscriminantAnalysis(store_covariance=True).fit(X_train, y_train)'

models_list = {"lr" :lr, "svm":svm, "dt": dt,  "knn":knn, "nb":nb, "lda":lda, "qda":qda}
models_list

{'lr': 'LogisticRegression().fit(X_train, y_train)',
 'svm': 'SVC(gamma="scale", kernel="rbf").fit(X_train, y_train)',
 'dt': 'DecisionTreeClassifier(criterion="gini", max_depth=4).fit(X_train, y_train)',
 'knn': 'KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)',
 'nb': 'GaussianNB().fit(X_train, y_train)',
 'lda': 'LinearDiscriminantAnalysis(solver="svd", store_covariance=True).fit(X_train, y_train)',
 'qda': 'QuadraticDiscriminantAnalysis(store_covariance=True).fit(X_train, y_train)'}

In [37]:
train_models_list = {}

for model_name, model in models_list.items():
    boot = resample(dataset, replace=True, n_samples=200, random_state=2020)
    X_train = boot.drop('Estado', axis = 1)
    y_train = boot.Estado
    train_model = eval(model)
    train_models_list[model_name] = train_model
    
train_models_list

c:\Users\Usuario\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Usuario\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:808: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

{'lr': LogisticRegression(),
 'svm': SVC(),
 'dt': DecisionTreeClassifier(max_depth=4),
 'knn': KNeighborsClassifier(),
 'nb': GaussianNB(),
 'lda': LinearDiscriminantAnalysis(store_covariance=True),
 'qda': QuadraticDiscriminantAnalysis(store_covariance=True)}

In [38]:
auc_scores = {}
results_matrix = pd.DataFrame(columns=np.arange(0, len(y_test), 1).tolist())

for model_name, train_model in train_models_list.items():
    predicciones = train_model.predict(X_test)
    auc = roc_auc_score(y_test, predicciones)
    auc_scores[model_name] = auc
    tempDf = pd.DataFrame(predicciones).T
    results_matrix = results_matrix.append(tempDf)
    
    
    
results_matrix.index=list(train_models_list.keys())

 
results_matrix

,0,1,2,3,4,5,6,7,8,9,...,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927
lr,1,0,0,1,1,1,1,0,1,0,...,1,1,0,1,0,0,0,1,0,0
svm,1,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
dt,1,0,0,1,1,1,1,0,1,0,...,1,1,0,1,0,0,0,1,0,0
knn,1,1,0,0,0,0,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0
nb,1,0,0,1,1,1,1,1,1,0,...,1,1,0,1,0,0,0,1,0,0
lda,1,0,0,1,1,1,1,0,1,0,...,1,1,0,1,0,0,0,1,0,0
qda,1,0,0,1,1,1,1,0,1,0,...,1,1,0,1,0,0,0,1,0,0

In [39]:
votacion = results_matrix.apply(pd.value_counts)
votacion

,0,1,2,3,4,5,6,7,8,9,...,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927
0,NaN,6,7.0,2,2,2,2,5,NaN,6,...,1,2,7.0,2,7.0,7.0,7.0,2,7.0,7.0
1,7.0,1,NaN,5,5,5,5,2,7.0,1,...,6,5,NaN,5,NaN,NaN,NaN,5,NaN,NaN

In [40]:
final_predictions = []

for (columnName, columnData) in votacion.iteritems():
    column_result = columnData.values
    final_predictions.append(np.nanargmax(column_result, axis=0))

final_predictions

[1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 ...]

In [41]:
auc = roc_auc_score(y_test, final_predictions)
auc

0.9891846921797005

In [42]:
auc_scores

{'lr': 0.9916805324459235,
 'svm': 0.5195209545156604,
 'dt': 0.9945923460898503,
 'knn': 0.5812190884797147,
 'nb': 0.978369384359401,
 'lda': 0.9932149356215307,
 'qda': 0.9850249584026622}

In [45]:
svm = GridSearchCV(SVC(), {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']}, cv=10).fit(X_train, y_train)
randomForest = GridSearchCV(RandomForestClassifier(), {'n_estimators': [20, 50, 100, 500, 1000], 
                                                        'max_depth': [10, 100, 500]}).fit(X_train, y_train)

In [43]:
svmResults = pd.DataFrame(svm.cv_results_)

AttributeError: 'str' object has no attribute 'cv_results_'

In [ ]:
svmResults = pd.DataFrame(svm.cv_results_)
svmResults.sort_values('rank_test_score', ascending=True)

In [ ]:
randomForest.cv_results_